// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OriginsOfDestiny.Data;

#nullable disable

namespace OriginsOfDestiny.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250104173433_DeactivationPlayers3")]
    partial class DeactivationPlayers3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OriginsOfDestiny.Models.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Mana")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Character", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("OriginsOfDestiny.Models.Dialogs.Dialog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("NeedReplace")
                        .HasColumnType("boolean");

                    b.Property<Dictionary<string, string>>("Responses")
                        .HasColumnType("hstore");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dialogs");
                });

            modelBuilder.Entity("OriginsOfDestiny.Models.Sessions.UserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActiveDialogId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDialogId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("OriginsOfDestiny.Models.Characters.Player", b =>
                {
                    b.HasBaseType("OriginsOfDestiny.Models.Characters.Character");

                    b.Property<DateTime?>("DeactivationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Expirience")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("OriginsOfDestiny.Models.Sessions.UserSession", b =>
                {
                    b.HasOne("OriginsOfDestiny.Models.Dialogs.Dialog", "ActiveDialog")
                        .WithMany("Sessions")
                        .HasForeignKey("ActiveDialogId");

                    b.Navigation("ActiveDialog");
                });

            modelBuilder.Entity("OriginsOfDestiny.Models.Characters.Player", b =>
                {
                    b.HasOne("OriginsOfDestiny.Models.Characters.Character", null)
                        .WithOne()
                        .HasForeignKey("OriginsOfDestiny.Models.Characters.Player", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OriginsOfDestiny.Models.Sessions.UserSession", "Session")
                        .WithOne("Player")
                        .HasForeignKey("OriginsOfDestiny.Models.Characters.Player", "TelegramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OriginsOfDestiny.Models.Dialogs.Dialog", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("OriginsOfDestiny.Models.Sessions.UserSession", b =>
                {
                    b.Navigation("Player")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
